In [3]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score 
from sklearn.metrics import confusion_matrix, precision_recall_curve, roc_curve, auc, log_loss
from sklearn.ensemble import GradientBoostingClassifier

In [4]:
final_train = pd.read_csv("train_processed.csv")
final_train.head(5)

,srch_id,site_id,visitor_location_country_id,prop_country_id,prop_id,prop_starrating,prop_review_score,prop_brand_bool,prop_location_score1,prop_log_historical_price,...,price_usd,promotion_flag,srch_destination_id,srch_length_of_stay,srch_booking_window,srch_adults_count,srch_children_count,srch_room_count,srch_saturday_night_bool,label
0,1,12,187,219,893,3,3.5,1,2.83,4.95,...,104.77,0,23246,1,0,4,0,1,1,0
1,1,12,187,219,56880,4,4.0,1,2.83,5.15,...,280.69,0,23246,1,0,4,0,1,1,0
2,1,12,187,219,74474,3,4.5,1,2.40,5.03,...,210.84,0,23246,1,0,4,0,1,1,0
3,1,12,187,219,68914,2,3.0,1,2.20,4.44,...,100.89,0,23246,1,0,4,0,1,1,5
4,4,5,219,219,139893,2,3.0,1,1.61,5.25,...,129.00,0,12588,2,46,1,0,1,1,1

In [5]:
X = final_train.drop("label", axis=1)
y = final_train['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

In [6]:
final_train.replace([np.inf, -np.inf], np.nan, inplace=True)
final_train.fillna(0, inplace=True)

In [7]:
final_train.iloc[214695]

srch_id                        161191.00
site_id                             5.00
visitor_location_country_id       219.00
prop_country_id                   219.00
prop_id                         79507.00
prop_starrating                     3.00
prop_review_score                   3.00
prop_brand_bool                     1.00
prop_location_score1                0.00
prop_log_historical_price           5.18
position                            4.00
price_usd                         134.00
promotion_flag                      0.00
srch_destination_id             20477.00
srch_length_of_stay                 1.00
srch_booking_window                 3.00
srch_adults_count                   1.00
srch_children_count                 1.00
srch_room_count                     2.00
srch_saturday_night_bool            0.00
label                               5.00
Name: 214695, dtype: float64

In [8]:
!pip install pyyaml h5py

Requirement already satisfied: pyyaml in c:\users\joaqu\anaconda3\lib\site-packages (5.3.1)
Requirement already satisfied: h5py in c:\users\joaqu\anaconda3\lib\site-packages (2.10.0)
Requirement already satisfied: numpy>=1.7 in c:\users\joaqu\anaconda3\lib\site-packages (from h5py) (1.19.2)
Requirement already satisfied: six in c:\users\joaqu\anaconda3\lib\site-packages (from h5py) (1.15.0)

In [11]:
gbc = GradientBoostingClassifier()

scores_accuracy = cross_val_score(gbc, X, y, cv=10, scoring='accuracy')

In [12]:
print('K-fold cross-validation results:')
print(gbc.__class__.__name__+" average accuracy is %2.3f" % scores_accuracy.mean())

K-fold cross-validation results:
GradientBoostingClassifier average accuracy is 0.536

In [13]:
final_test = pd.read_csv("test_processed.csv", sep = ',')

In [14]:
final_test.replace([np.inf, -np.inf], np.nan, inplace=True)
final_test.fillna(0, inplace=True)

In [15]:
final_test.head(20)

,srch_id,site_id,visitor_location_country_id,prop_country_id,prop_id,prop_starrating,prop_review_score,prop_brand_bool,prop_location_score1,prop_log_historical_price,price_usd,promotion_flag,srch_destination_id,srch_length_of_stay,srch_booking_window,srch_adults_count,srch_children_count,srch_room_count,srch_saturday_night_bool
0,1,24,216,219,3180,3,4.5,1,2.94,5.03,119.00,0,19222,1,10,2,0,1,0
1,1,24,216,219,5543,3,4.5,1,2.64,4.93,118.00,0,19222,1,10,2,0,1,0
2,1,24,216,219,14142,2,3.5,1,2.71,4.16,49.00,0,19222,1,10,2,0,1,0
3,1,24,216,219,22393,3,4.5,1,2.40,5.03,143.00,0,19222,1,10,2,0,1,0
4,1,24,216,219,24194,3,4.5,1,2.94,4.72,79.00,0,19222,1,10,2,0,1,0
5,1,24,216,219,28181,3,4.5,1,2.30,4.68,84.15,0,19222,1,10,2,0,1,0
6,1,24,216,219,34263,3,4.5,1,3.09,4.63,79.00,0,19222,1,10,2,0,1,0
7,1,24,216,219,37567,2,4.5,0,2.83,4.21,52.40,1,19222,1,10,2,0,1,0
8,1,24,216,219,50162,2,3.5,1,2.20,4.36,49.99,1,19222,1,10,2,0,1,0
9,1,24,216,219,54937,3,4.0,1,2.08,4.75,83.30,1,19222,1,10,2,0,1,0
10,1,24,216,219,56050,3,4.0,1,2.77,4.59,145.00,0,19222,1,10,2,0,1,0
11,1,24,216,219,61632,0,0.0,0,3.04,4.62,45.00,0,19222,1,10,2,0,1,0
12,1,24,216,219,61934,3,4.5,1,2.89,4.69,88.88,1,19222,1,10,2,0,1,0
13,1,24,216,219,63894,3,4.5,1,2.77,4.88,103.98,0,19222,1,10,2,0,1,0
14,1,24,216,219,72090,3,4.0,1,2.89,4.95,79.00,0,19222,1,10,2,0,1,0
15,1,24,216,219,73666,3,4.5,1,2.89,4.79,149.00,0,19222,1,10,2,0,1,0
16,1,24,216,219,74045,3,4.0,1,2.77,4.56,89.99,0,19222,1,10,2,0,1,0
17,1,24,216,219,78599,4,4.5,1,2.30,5.06,158.87,0,19222,1,10,2,0,1,0
18,1,24,216,219,82231,3,4.5,1,2.77,4.92,104.00,0,19222,1,10,2,0,1,0
19,1,24,216,219,89466,2,3.0,0,2.08,4.31,58.57,0,19222,1,10,2,0,1,0

In [16]:
selectedfeatures = ["srch_id", "site_id", "visitor_location_country_id", "prop_country_id", "prop_id", "prop_starrating", "prop_review_score", "prop_brand_bool", "prop_location_score1", "prop_log_historical_price", "price_usd", "promotion_flag", "srch_destination_id", "srch_length_of_stay", "srch_booking_window", "srch_adults_count", "srch_children_count", "srch_room_count", "srch_saturday_night_bool"]

In [ ]:
gbc.max_iter = 10000
gbc.fit(X, y)

In [ ]:
final_test['label'] = gbc.predict(final_test[selectedfeatures])

In [ ]:
final_test.sort_values(["srch_id","label"],ascending=[True,False], inplace=True)

In [ ]:
submission = final_test[['srch_id','prop_id']]

In [ ]:
submission.to_csv("C:/Users/joaqu/pythonProject/DMT2/submission_gbc.csv",index=False)